name: GLaDOS-CheckIn

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
      - 'imgs/**'
  schedule:
    - cron: 30 1 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl
          sudo apt-get install -y libx11-dev libx11-xcb-dev libxcomposite-dev \
                                libxdamage-dev libxrandr-dev libasound2 libatk1.0-0 \
                                libcups2 libgdk-pixbuf2.0-0 libnspr4 libnss3 libxtst6 \
                                libappindicator3-1 libgbm-dev libxss1 libgdk-pixbuf2.0-0

      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: install axios
        run: npm install axios

      - name: install puppeteer-extra-plugin-stealth
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Update Puppeteer to the latest version
        run: npm install puppeteer@latest

      - name: CheckIn
        run: node checkin.js
        env:
          DEBUG: puppeteer:*
          PUSHPLUS: ${{ secrets.PUSHPLUS }}
          COOKIES: ${{ secrets.COOKIES }}

      - name: keep alive
        uses: gautamkrishnar/keepalive-workflow@master

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 10
          delete_run_by_conclusion_pattern: success
